name: Mirror main to dradns (SDLC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  TARGET_REPO: dradns/SDLC3.0-landing

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to team lead repo (main → main)
        env:
          TARGET_TOKEN: ${{ secrets.DRADNS_PAT }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote remove teamlead 2>/dev/null || true
          git remote add teamlead "https://x-access-token:${TARGET_TOKEN}@github.com/${TARGET_REPO}.git"
          git remote -v | sed 's/x-access-token:.*@/x-access-token:***@/'
          git push teamlead HEAD:main --force
