name: Mirror main to team lead

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to team lead repo (main → main)
        env:
          TARGET_TOKEN: ${{ secrets.TEAMLEAD_PAT }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # целевой репозиторий dradns
          TARGET_REPO="dradns/SDLC3.0-landing"

          # добавляем удалённый с https + PAT
          git remote add teamlead https://x-access-token:${TARGET_TOKEN}@github.com/${TARGET_REPO}.git

          # пушим только ветку main (без --force)
          git push teamlead HEAD:main
